### ISSUE TITLE
iOS Firebase dependencies cause App Store rejection

### ISSUE THREAD

**Issue by nyakaspeter** [JimmyPun610/BarcodeScanner.XF#32]
Older versions of Xamarin.Firebase.iOS.Auth contain references to the deprecated UIWebView API. Apple no longer accepts App Store publications with the following message:

"ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). "

Newer versions of the package supposedly fixed the issue, according to [this issue](https://github.com/xamarin/GoogleApisForiOSComponents/issues/341). Can you please update the dependencies in your package?

**Comment by JimmyPun610** [comment]
The package is updated and build successfully according to AppCenter.
But I have not test it yet, please do me a favour on testing it.

Please use 4.6.0.1 with XF 4.6+ and read about readme.md as there is additional settings in your AppDelegate.cs

**Comment by nyakaspeter** [comment]
It builds fine with XF 4.6.726 (not with the newly released 4.6.772 sadly). But I get NullReferenceException when I try to set RemoteConfig.SharedInstance.ConfigSettings in AppDelegate.cs.

**Comment by JimmyPun610** [comment]
> It builds fine with XF 4.6.726 (not with the newly released 4.6.772 sadly). But I get NullReferenceException when I try to set RemoteConfig.SharedInstance.ConfigSettings in AppDelegate.cs.

I made mistake on the calling sequence, please do it in below sequence
```C#
Firebase.Core.App.Configure();
RemoteConfig.SharedInstance.ConfigSettings = new RemoteConfigSettings();
```

**Comment by JimmyPun610** [comment]
Just finding some error after update.
Working on it

**Comment by JimmyPun610** [comment]
@nyakaspeter 
So I finished update and testing on iOS.
Please use 4.6.0.2 and it should be working now.
Please let me know if there is any issue.

(I do not have Android to test)

**Comment by remco-rebelit** [comment]
Hi I have updated to 4.6.0.1 with XF 4.6+ but I am still facing this issue. Is there something I should check?

**Comment by JimmyPun610** [comment]
@remco-rebelit 
You can rebuild all to try. If it is not working, you may need to check if there is any code is using UIWebView.

**Comment by remco-rebelit** [comment]
I removed all obj and bin folders and I am still getting the App Store rejection because of ITMS-90809: Deprecated API Usage. There is no code using UIWebView.

**Comment by JimmyPun610** [comment]
@remco-rebelit 
How about if you remove my package and submit?
I think there is a library using uiwebview but you may need to try it one by one.

**Comment by remco-rebelit** [comment]
Thanks, I solved it by adding: --optimize=experimental-xforms-product-type as additional touch arguments.

**Comment by JimmyPun610** [comment]
> Thanks, I solved it by adding: --optimize=experimental-xforms-product-type as additional touch arguments.

good to know that.

Similar issue for reference
https://forums.xamarin.com/discussion/179071/deprecated-uiwebview

**Comment by nyakaspeter** [comment]
I've tested 4.6.0.2 on both Android & iOS. It works great now. Thanks for the fast response.
